### ISSUE TITLE
materials => blocks

### ISSUE THREAD

**Issue by afc163** [umijs/umi-blocks#1]
要不要换 blocks 这个名字，对标 https://www.froala.com/design-blocks

中文可以不变。

https://documentation.concrete5.org/developers/concepts/front-end-content

**Comment by sorrycc** [comment]
我觉得可以，命令行和仓库叫 block。

**Comment by okoala** [comment]
block +1，拼写也比 materials 简单~

**Comment by yutingzhao1991** [comment]
那这样感觉英文和中文对不上，https://www.froala.com/design-blocks 这个上面就是区块的意思吧。

**Comment by yutingzhao1991** [comment]
我还是感觉 material 比较好一点，block 就是区块的意思如果说英文是 block 但是中文用物料感觉有点奇怪。如果要改是不是中文也叫区块好一点，umi 区块？

关于 material 比较难写这个问题我觉得这个只是对于非英文国家的开发来说有这个问题，其实它和 generate 的字母数是一样的。而且在命令行中我们提供了 m 这个快捷命令，感觉问题不大。

**Comment by afc163** [comment]
material 不是我们提到的物料的意思，材质/质地更准确。block 更贴切我们的需求。

**Comment by yutingzhao1991** [comment]
似乎也对，@picodoth 有没有什么想法？

先缓一缓，没有其它异议的话我最后再统一改。
