### ISSUE TITLE
消除区块中 @ 下的代码

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/umi-blocks#12]
尝试把 ant-design-pro 下的 @ 下的依赖抽取到 ant-design-pro 中，当前遗留的有：

- components/PageLoading
- utils/utils
- utils/Yuan.js
- utils/utils.less
- components/PageHeaderWrapper
- components/StandardTable
- components/StandardFormRow
- components/ArticleListContent
- components/ActiveChart

**Comment by xiaohuoni** [comment]
- 尝试把 ant-design-pro 下的 @ 下的依赖抽取到 ant-design-pro 中
@yutingzhao1991 是不是写错了

**Comment by yutingzhao1991** [comment]
> 尝试把区块 @ 下的依赖抽取到 ant-design-pro 中，当前遗留的有：

这个已经弄完了。

**Comment by xiaohuoni** [comment]
👍
