### ISSUE TITLE
umi block 自有仓库能否简化命令

### ISSUE THREAD

**Issue by ql434** [umijs/umi-blocks#15]
目前操作：
`umi block add git@gitlab.alibaba-inc.com:alitx-service/umi-blocks/tree/master/admin-console/tableServer  --path=/ops/open/supplier --npm-client=tnpm`

能否在当前项目下的umijs里面，增加仓库别名；
期望：`umi block add xxx/tableServer --path=/ops/open/supplier `

**Comment by sorrycc** [comment]
我觉得可以提供一些配置，放在脚手架里，

```js
export default {
  block: {
    registry: 'git@gitlab.alibaba-inc.com:alitx-service',
  },
  npmClient: 'tnpm',
}
```

@yutingzhao1991

**Comment by yutingzhao1991** [comment]
现在有途径可以通过 `_modifyCommand` 这个插件的方法解决。不过感觉加一个 `block` 配置也确实可以，或者在 `umi-plugin-pro-block` 这里面实现。

**Comment by ql434** [comment]
> 现在有途径可以通过 `_modifyCommand` 这个插件的方法解决。不过感觉加一个 `block` 配置也确实可以，或者在 `umi-plugin-pro-block` 这里面实现。

有列入到开发计划里面去吗？

**Comment by chenshuai2144** [comment]
已经支持
