### ISSUE TITLE
umi block list 列出的包名是错误的

### ISSUE THREAD

**Issue by liran** [umijs/umi-blocks#20]
运行 `umi block list`
  Blocks:

    ant-design-pro\AccountCenter
    ant-design-pro\AccountSettings
    ant-design-pro\AdvancedForm
    ant-design-pro\AdvancedProfile
    ant-design-pro\Analysis
    ant-design-pro\BasicForm
    ant-design-pro\BasicList
    ant-design-pro\BasicProfile
    ant-design-pro\CardList
    ant-design-pro\Exception403
    ant-design-pro\Exception404
    ant-design-pro\Exception500
    ant-design-pro\Monitor
    ant-design-pro\ResultFail
    ant-design-pro\ResultSuccess
    ant-design-pro\SearchListApplications
    ant-design-pro\SearchListArticles
    ant-design-pro\SearchListProjects
    ant-design-pro\StepForm
    ant-design-pro\TableList
    ant-design-pro\UserLogin
    ant-design-pro\UserRegister
    ant-design-pro\UserRegisterResult
    ant-design-pro\Workplace
    blank
    demo
    user-dashboard

上面的反斜杠“\”应该变成正斜杠"/"。比如：ant-design-pro\AccountCenter  => ant-design-pro/AccountCenter 。

**Comment by sorrycc** [comment]
系统是 windows 吗？

**Comment by liran** [comment]
是的，win10。

**Comment by gisfinder** [comment]
这个杠杠确实反了，如果用list出来的add不上。

**Comment by chenshuai2144** [comment]
已修复
