### ISSUE TITLE
block的antd-pro组件是否会考虑出一套tsx的？

### ISSUE THREAD

**Issue by liujians** [umijs/umi-blocks#22]

**Comment by afc163** [comment]
已经有了：https://github.com/ant-design/pro-blocks/

**Comment by liujians** [comment]
@afc163 看了一下有一半的组件是tsx，下面的组件比如tablelist,stepform等都不是TSX

**Comment by liujians** [comment]
README中的add block的地址也跟这边的一样，执行完拉的是这边的

**Comment by afc163** [comment]
js => 到 ts 正在迁移中，v4 完成后 umi 这边会改成直接用 pro-blocks

**Comment by liujians** [comment]
👌好的，谢谢。目前已经在用github url的形式用那些迁移完成的block了

**Comment by afc163** [comment]
@liujians 欢迎来一起改

https://github.com/ant-design/ant-design-pro/issues/3789
