### ISSUE TITLE
umi block add 区块,报错

### ISSUE THREAD

**Issue by zjj1063215024** [umijs/umi-blocks#25]
使用 create umi  选择的 app 无法 add 区块
而选择 ant-design-pro 则 可以添加区块
![image](https://user-images.githubusercontent.com/18130452/57498243-b8943300-730d-11e9-9b83-9103ef054321.png)

**Comment by zjj1063215024** [comment]
> 使用 create umi 选择的 app 无法 add 区块
> 而选择 ant-design-pro 则 可以添加区块

![image](https://user-images.githubusercontent.com/18130452/57498169-73700100-730d-11e9-8066-7a25fb70bf45.png)
$ sudo umi block add https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/UserLogin
✔ Parse url and args
✔ Git fetch
✔ Git checkout master
✔ Git pull
✖ Install additional dependencies ant-design-pro@^2.1.1,antd@^3.10.9,dva@^2.4.0,moment@^2.22.2,query-string@^6.0.0,umi-request@^1.0.0 with yarn
✖  error     Error: Error: Command failed: yarn add ant-design-pro@^2.1.1 antd@^3.10.9 dva@^2.4.0 moment@^2.22.2 query-string@^6.0.0 umi-request@^1.0.0 
error eslint@5.16.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "8.9.3"
error Found incompatible module

yarn add v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at /Users/zh_606/Desktop/Demo/umi-stag/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:316:21
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/Users/zh_606/Desktop/Demo/umi-stag/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:36:103)
    at _throw (/Users/zh_606/Desktop/Demo/umi-stag/node_modules/umi-build-dev/lib/plugins/commands/block/index.js:38:291)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by afc163** [comment]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/507615/57498753-b92dc900-730f-11e9-8e5d-2c5182f25a6a.png">

**Comment by zjj1063215024** [comment]
我使用的 8.11.1
