### ISSUE TITLE
添加官方block报错， not a git repository

### ISSUE THREAD

**Issue by saltdg** [umijs/umi-blocks#30]
umi block list 能看到列表

Blocks:
   ant-design-pro\AccountCenter
   ...

直接执行 umi block add ant-design-pro/AccountCenter 报错：

√ Parse url and args
× Git fetch
×  error     Error: Error: Command failed: git fetch
fatal: not a git repository (or any of the parent directories): .git

**Comment by mrzhangboss** [comment]
似乎添加全部路径有效
例如
`umi block add https://github.com/umijs/umi-blocks/tree/master/ant-design-pro/AccountCenter`

**Comment by MI-Class** [comment]
直接使用“umi block add AccountCenter”

**Comment by sohui** [comment]
> 直接使用“umi block add AccountCenter”
这个命令也不能正常工作。

**Comment by chenshuai2144** [comment]
尝试使用 umi block clear
