### ISSUE TITLE
umi block add 不支持本地部署的gitlab

### ISSUE THREAD

**Issue by MI-Class** [umijs/umi-blocks#32]
umi block add 不支持本地部署的gitlab，会提示 can`t match any pattern

**Comment by ItxiaoDz** [comment]
我用gitblit也遇到了这个问题。无论版本库是否有权限控制

**Comment by MI-Class** [comment]
> 我用gitblit也遇到了这个问题。无论版本库是否有权限控制

我在https://github.com/umijs/umi/pull/2559 提交了一个修复，因为他限定了前缀必须是gitlab和github，自己搭建的不行，过滤的正则里面加入ip地址的过滤就可以了
