### ISSUE TITLE
把 blocks 发到 npm 上

### ISSUE THREAD

**Issue by afc163** [umijs/umi-blocks#37]
好处：

- [x] 快。GitHub 太慢。
- [x] 解决内网 gitlab 权限问题。
- [x] 可以利用 unpkg 服务直接生成 html 预览：https://unpkg.com/@icedesign/user-profile-card-block/build/index.html

坏处：

- [x] 多一步发布过程。

**Comment by yutingzhao1991** [comment]
要 umi 先支持下 npm 包 https://github.com/umijs/umi/issues/2646

**Comment by sorrycc** [comment]
在 https://github.com/umijs/umi/issues/2646 讨论吧。
