### ISSUE TITLE
为什么这个项目不再更新了？

### ISSUE THREAD

**Issue by GeoDaoyu** [umijs/umi-blocks#60]
是有新的方案/仓库了么？
还是现在的区块方案有什么无法解决的问题，导致这个仓库不再更新了？
能提供一些博文之类的资料供参考吗？

**Comment by yutingzhao1991** [comment]
实际用下来发现收益不大，区块使用和维护成本高，代码拉下来之后通常都需要做比较多的改动，提效的意义不大。

最后总结出了一套 pro 组件更适用，可以看看 https://procomponents.ant.design/ 这个。

**Comment by GeoDaoyu** [comment]
好的，感谢你的答复。我也有在使用antd pro，它很好用。
我其实是想管理我自己的区块，你提到的【使用和维护成本高】将成为我重要的参考意见。
